### ISSUE TITLE
Argument 1 passed to DH\\Auditor\\Model\\Entry::sort() must be of the type array, null given

### ISSUE THREAD

**Issue by tomme87** [DamienHarper/auditor#18]
| Q                    | A
| ---------------------| -----------------------
| `auditor` version    | 4.0.3
| PHP version          | 7.3
| Database             | MariaDB

#### Summary

> Argument 1 passed to DH\\Auditor\\Model\\Entry::sort() must be of the type array, null given, called in /var/www/app/vendor/damienharper/auditor/src/Model/Entry.php on line 160

When viewing audit log for an entity that have done a insert and does not have any diff.

#### How to reproduce

Use the viewer and press "view audit" on a entity with entries that do not have a diff.

#### Expected behavior

Not an error

**Comment by tomme87** [comment]
Some additional info: this only seams to happen if the entity have binary data. if I ignore the property with binary data the problem disappears, since `diffs` is no longer empty. Looks like serializing binary data is not working, and fails silently, causing `diffs` to be empty.

**Comment by DamienHarper** [comment]
@tomme87 Thanks for the report, I'll have a look asap!

**Comment by DamienHarper** [comment]
@tomme87 could you please check/test `master` branch, it should fix this issue.

**Comment by DamienHarper** [comment]
@tomme87 did you have any chance to test `master` branch?

**Comment by tomme87** [comment]
@DamienHarper I'm sorry, I did not get the time. I will check later today

**Comment by DamienHarper** [comment]
@tomme87 did you have any chance to test master branch?

**Comment by tomme87** [comment]
Sorry, something came up and I forgot. I have tested a bit now, but it's still not working for me. I suspect that this is because I was not accurate enough in my description of my problem. Since the binary data I put in the database is not actually a resource, it's just a string that contains binary data. in fact it's a UUID, see https://github.com/ramsey/uuid-doctrine/blob/master/src/UuidBinaryType.php for the exact doctrine type I'm using. Sorry for not mentioning this in my original issue.

I have done some testing and doing  `$diffs = json_encode($data['diff'], JSON_INVALID_UTF8_IGNORE);` in TransactionProcessor seams to fix the issue, but I'm not sure it's a good solution.

**Comment by DamienHarper** [comment]
@tomme87 thanks for your feedback, I just pushed some changes that bring support of Ramsey UUIDs as well as Symfony UIDs (UUID and ULID). May you check `master`, it should fix this issue?

**Comment by tomme87** [comment]
@DamienHarper it works! Exactly like I wanted it, nice work. Thanks :slightly_smiling_face:

**Comment by DamienHarper** [comment]
@tomme87 Great so I close this issue
